import Head from "next/head";
import Articles from "../components/articles/Articles";
import axios from "axios";

export default function Home({ apiData }) {
  return (
    <div>
      <Head>
        <title>Newly News - the newliest news</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Articles apiData={apiData} />
    </div>
  );
}

// business entertainment generalhealth science sports technology

export async function getServerSideProps(context) {
  // const router = useRouter();
  const category = context.query.category ? context.query.category : "general";
  const { data } = await axios({
    url: `https://newsapi.org/v2/top-headlines?category=${category}`,
    headers: {
      "X-Api-Key": process.env.API_KEY,
    },
  });
  const apiData = data;
  return {
    props: { apiData },
  };
}
